# Generated by Django 6.0.4 on 2026-05-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=16, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('ubudehe_category', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True)),
                ('ml_risk_profile', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('registration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('deregistered_at', models.DateTimeField(blank=True, null=True)),
                ('deregister_reason', models.CharField(blank=True, choices=[('NO_LONGER_ELIGIBLE', 'No Longer Eligible'), ('COW_DIED', 'Cow Died'), ('RULE_VIOLATION', 'Rule Violation'), ('RELOCATED', 'Relocated'), ('VOLUNTARY', 'Voluntary'), ('DECEASED', 'Beneficiary Deceased'), ('LAND_LOSS', 'Loss of Land')], max_length=30, null=True)),
                ('deregister_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beneficiaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
