# Generated by Django 6.0.4 on 2026-05-01 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('districts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='deregistered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deregistrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaries', to='districts.district'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['national_id'], name='beneficiari_nationa_dc1566_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['district'], name='beneficiari_distric_21d18c_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['is_active'], name='beneficiari_is_acti_c9a840_idx'),
        ),
    ]
