"""Report generation tasks — Cloudinary storage, Resend email delivery."""
from celery import shared_task
import logging

logger = logging.getLogger(__name__)


@shared_task(name="features.reports.tasks.generate_report_pdf")
def generate_report_pdf(report_id: int):
    from .models import Report
    from django.utils import timezone
    from features.cows.models import Cow
    from features.beneficiaries.models import Beneficiary
    from features.alerts.models import Alert
    from shared.cloudinary_utils import upload_report_pdf

    try:
        report = Report.objects.select_related("generated_by", "district").get(id=report_id)
        report.status = "GENERATING"
        report.save(update_fields=["status"])

        # Build data snapshot
        qs_cows = Cow.objects.filter(is_alive=True)
        qs_bens = Beneficiary.objects.filter(is_active=True)
        if report.district:
            qs_cows = qs_cows.filter(district=report.district)
            qs_bens = qs_bens.filter(district=report.district)

        data = {
            "total_cows":         qs_cows.count(),
            "total_beneficiaries":qs_bens.count(),
            "at_risk_cows":       qs_cows.filter(health_status__in=["AT_RISK","HIGH_RISK","CRITICAL","EMERGENCY"]).count(),
            "critical_cows":      qs_cows.filter(health_status__in=["CRITICAL","EMERGENCY"]).count(),
            "deceased_cows":      Cow.objects.filter(is_alive=False).count(),
            "unresolved_alerts":  Alert.objects.filter(is_resolved=False).count(),
            "report_type":        report.report_type,
            "period_start":       str(report.period_start),
            "period_end":         str(report.period_end),
            "district":           report.district.district_name if report.district else "National",
            "generated_at":       timezone.now().isoformat(),
        }

        # Build HTML report
        rows = "".join(
            f"<tr><td style='padding:10px;border-bottom:1px solid #e5e7eb;'>{k.replace('_',' ').title()}</td>"
            f"<td style='padding:10px;border-bottom:1px solid #e5e7eb;text-align:right;font-weight:bold;'>{v}</td></tr>"
            for k, v in data.items()
        )
        scope = report.district.district_name if report.district else "National"
        html_content = f"""<!DOCTYPE html><html><body style="font-family:Arial,sans-serif;padding:40px;max-width:700px;margin:0 auto;">
        <div style="border-bottom:3px solid #166534;padding-bottom:16px;margin-bottom:24px;">
          <h1 style="color:#166534;margin:0;">🐄 Girinka Pulse</h1>
          <h2 style="margin:4px 0;">{report.report_type.replace('_',' ').title()}</h2>
          <p style="color:#6B7280;margin:0;">{scope} — {report.period_start} to {report.period_end}</p>
        </div>
        <table style="width:100%;border-collapse:collapse;">{rows}</table>
        <p style="color:#9CA3AF;font-size:11px;margin-top:40px;">
          Auto-generated by Girinka Pulse AI System — Rwanda Agriculture Board (RAB)
        </p></body></html>"""

        # Upload to Cloudinary
        filename = f"report_{report_id}_{report.report_type}.html"
        url = upload_report_pdf(
            html_content.encode("utf-8"),
            filename=filename,
            folder="girinka/reports",
        )

        report.data_snapshot = data
        report.file_url      = url or ""
        report.status        = "READY"
        report.generated_at  = timezone.now()
        report.save()
        logger.info(f"Report {report_id} ready: {url}")

        # Email the requester
        if report.generated_by and report.generated_by.email:
            from features.notifications.utils import send_weekly_report_email
            send_weekly_report_email(
                to=report.generated_by.email,
                report_type=report.report_type,
                period=f"{report.period_start} → {report.period_end}",
                stats=data,
                download_url=url or "",
            )

    except Exception as e:
        Report.objects.filter(id=report_id).update(status="FAILED")
        logger.error(f"Report {report_id} failed: {e}")


@shared_task(name="features.reports.tasks.send_weekly_district_reports")
def send_weekly_district_reports():
    from features.districts.models import District
    from .models import Report
    from datetime import date, timedelta

    for d in District.objects.all():
        r = Report.objects.create(
            district=d,
            report_type="DISTRICT_WEEKLY",
            report_period="WEEKLY",
            period_start=date.today() - timedelta(days=7),
            period_end=date.today(),
        )
        generate_report_pdf.delay(r.id)
    logger.info("Weekly district reports queued.")


@shared_task(name="features.reports.tasks.send_weekly_national_report")
def send_weekly_national_report():
    from .models import Report
    from datetime import date, timedelta

    r = Report.objects.create(
        report_type="NATIONAL_MONTHLY",
        report_period="WEEKLY",
        period_start=date.today() - timedelta(days=7),
        period_end=date.today(),
    )
    generate_report_pdf.delay(r.id)
    logger.info("National report queued.")
