# Generated by Django 6.0.4 on 2026-05-01 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=20, unique=True)),
                ('breed', models.CharField(choices=[('FRIESIAN', 'Friesian'), ('JERSEY', 'Jersey'), ('ANKOLE', 'Ankole'), ('ANKOLE_CROSS', 'Ankole Cross'), ('FRIESIAN_CROSS', 'Friesian Cross'), ('JERSEY_CROSS', 'Jersey Cross'), ('OTHER', 'Other')], default='FRIESIAN_CROSS', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('AT_RISK', 'At Risk'), ('HIGH_RISK', 'High Risk'), ('UNDER_TREATMENT', 'Under Treatment'), ('CRITICAL', 'Critical'), ('EMERGENCY', 'Emergency'), ('DECEASED', 'Deceased'), ('FLAGGED_FOR_REVIEW', 'Flagged for Review')], default='HEALTHY', max_length=20)),
                ('genetic_profile_id', models.CharField(blank=True, max_length=50, null=True)),
                ('mortality_risk_score', models.FloatField(blank=True, null=True)),
                ('origin_type', models.CharField(choices=[('DIRECT_PROGRAM', 'Direct Program'), ('BORN_ON_FARM', 'Born on Farm'), ('PASS_ON_RECEIVED', 'Pass-On Received')], default='DIRECT_PROGRAM', max_length=20)),
                ('is_alive', models.BooleanField(default=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('death_cause', models.TextField(blank=True, null=True)),
                ('lactation_number', models.IntegerField(default=1)),
                ('days_in_milk', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cows', to='beneficiaries.beneficiary')),
            ],
            options={
                'db_table': 'cows',
                'ordering': ['-created_at'],
            },
        ),
    ]
