# Generated by Django 6.0.4 on 2026-05-01 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cows', '0001_initial'),
        ('districts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='death_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deaths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cow',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cows', to='districts.district'),
        ),
        migrations.AddIndex(
            model_name='cow',
            index=models.Index(fields=['tag_number'], name='cows_tag_num_aba213_idx'),
        ),
        migrations.AddIndex(
            model_name='cow',
            index=models.Index(fields=['beneficiary'], name='cows_benefic_7251a1_idx'),
        ),
        migrations.AddIndex(
            model_name='cow',
            index=models.Index(fields=['health_status'], name='cows_health__035f73_idx'),
        ),
        migrations.AddIndex(
            model_name='cow',
            index=models.Index(fields=['is_alive'], name='cows_is_aliv_ce747f_idx'),
        ),
    ]
