# Generated by Django 6.0.4 on 2026-05-01 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cows', '0001_initial'),
        ('predictions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_yield', models.FloatField(blank=True, null=True)),
                ('evening_yield', models.FloatField(blank=True, null=True)),
                ('daily_yield', models.FloatField()),
                ('feed_amount', models.FloatField(blank=True, null=True)),
                ('water_intake', models.FloatField(blank=True, null=True)),
                ('lstm_forecast', models.FloatField(blank=True, null=True)),
                ('collection_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='cows.cow')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictions.aimodel')),
            ],
            options={
                'db_table': 'milk_production',
                'ordering': ['-collection_date'],
                'indexes': [models.Index(fields=['cow', 'collection_date'], name='milk_produc_cow_id_f1fc9c_idx')],
                'unique_together': {('cow', 'collection_date')},
            },
        ),
    ]
