# Generated by Django 6.0.4 on 2026-05-01 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('FARMER_SUMMARY', 'Farmer Summary'), ('DISTRICT_WEEKLY', 'District Weekly'), ('NATIONAL_MONTHLY', 'National Monthly'), ('VET_PRIORITY', 'Vet Priority'), ('PASS_ON_AUDIT', 'Pass-On Audit'), ('AI_PERFORMANCE', 'AI Performance')], max_length=30)),
                ('report_period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], max_length=10)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('data_snapshot', models.JSONField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='districts.district')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
