# Generated by Django 6.0.4 on 2026-05-01 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_id', models.BigIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_weight', models.FloatField(blank=True, null=True)),
                ('birth_health', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=12, null=True)),
                ('genetic_notes', models.TextField(blank=True, null=True)),
                ('generation_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lineage', to='cows.cow')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='cows.cow')),
            ],
            options={
                'db_table': 'lineage_records',
            },
        ),
    ]
