# Generated by Django 6.0.4 on 2026-05-01 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0002_initial'),
        ('cows', '0002_initial'),
        ('districts', '0001_initial'),
        ('passon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passonregistry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passon_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passonregistry',
            name='calf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passon_records', to='cows.cow'),
        ),
        migrations.AddField(
            model_name='passonregistry',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='districts.district'),
        ),
        migrations.AddField(
            model_name='passonregistry',
            name='donor_farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passon_donations', to='beneficiaries.beneficiary'),
        ),
        migrations.AddField(
            model_name='passonregistry',
            name='recipient_farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passon_receipts', to='beneficiaries.beneficiary'),
        ),
    ]
