# Generated by Django 6.0.4 on 2026-05-01 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0002_initial'),
        ('cows', '0001_initial'),
        ('predictions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='cow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cows.cow'),
        ),
        migrations.AddField(
            model_name='alert',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictions.aimodel'),
        ),
    ]
