from celery import shared_task
import logging

logger = logging.getLogger(__name__)


@shared_task(name="features.passon.tasks.generate_passon_certificate")
def generate_passon_certificate(transfer_id: int):
    """Generate pass-on certificate, upload to Cloudinary, email to both parties."""
    from .models import PassOnRegistry
    from features.notifications.utils import send_email

    try:
        transfer = PassOnRegistry.objects.select_related(
            "calf", "donor_farmer__user", "recipient_farmer__user",
            "district", "approved_by"
        ).get(id=transfer_id)

        # Build simple HTML certificate (production: use WeasyPrint for PDF)
        cert_html = f"""
        <html><body style="font-family:Arial;padding:40px;max-width:700px;margin:0 auto;border:3px solid #166534;">
        <div style="text-align:center;border-bottom:2px solid #166534;padding-bottom:20px;margin-bottom:20px;">
          <h1 style="color:#166534;">🐄 GIRINKA PULSE</h1>
          <h2>Pass-On Transfer Certificate</h2>
          <p style="color:#6B7280;">Republic of Rwanda — "One Cow Per Family" Program</p>
        </div>
        <p>This certifies that the following calf transfer has been completed:</p>
        <table style="width:100%;border-collapse:collapse;margin:20px 0;">
          <tr><td style="padding:8px;background:#F0FDF4;font-weight:bold;">Transfer ID</td><td style="padding:8px;">#{transfer.id}</td></tr>
          <tr><td style="padding:8px;background:#F0FDF4;font-weight:bold;">Calf Tag</td><td style="padding:8px;">{transfer.calf.tag_number}</td></tr>
          <tr><td style="padding:8px;background:#F0FDF4;font-weight:bold;">Breed</td><td style="padding:8px;">{transfer.calf.breed}</td></tr>
          <tr><td style="padding:8px;background:#F0FDF4;font-weight:bold;">Donor</td><td style="padding:8px;">{transfer.donor_farmer.full_name}</td></tr>
          <tr><td style="padding:8px;background:#F0FDF4;font-weight:bold;">Recipient</td><td style="padding:8px;">{transfer.recipient_farmer.full_name}</td></tr>
          <tr><td style="padding:8px;background:#F0FDF4;font-weight:bold;">District</td><td style="padding:8px;">{transfer.district.district_name}</td></tr>
          <tr><td style="padding:8px;background:#F0FDF4;font-weight:bold;">Transfer Date</td><td style="padding:8px;">{transfer.transfer_date}</td></tr>
          <tr><td style="padding:8px;background:#F0FDF4;font-weight:bold;">Approved By</td><td style="padding:8px;">{transfer.approved_by.full_name if transfer.approved_by else 'N/A'}</td></tr>
        </table>
        <div style="margin-top:40px;text-align:center;color:#6B7280;font-size:12px;">
          Generated by Girinka Pulse AI System — Rwanda Agriculture Board (RAB)
        </div>
        </body></html>
        """

        # Upload certificate HTML to Cloudinary as raw file
        from shared.cloudinary_utils import upload_certificate_pdf
        import io
        cert_bytes = cert_html.encode("utf-8")
        url = upload_certificate_pdf(cert_bytes, transfer_id)

        if url:
            transfer.certificate_url = url
            transfer.save(update_fields=["certificate_url"])
            logger.info(f"Certificate uploaded: {url}")

        # Email both donor and recipient
        recipients = []
        if transfer.donor_farmer.user and transfer.donor_farmer.user.email:
            recipients.append(transfer.donor_farmer.user.email)
        if transfer.recipient_farmer.user and transfer.recipient_farmer.user.email:
            recipients.append(transfer.recipient_farmer.user.email)

        if recipients:
            download_section = f'<p><a href="{url}" style="color:#166534;">📄 View Certificate</a></p>' if url else ""
            send_email(
                to=recipients,
                subject=f"Girinka Pass-On Certificate — Calf {transfer.calf.tag_number}",
                html=f"""
                <div style="font-family:Arial;padding:20px;max-width:600px;margin:0 auto;">
                  <h2 style="color:#166534;">🐄 Pass-On Transfer Complete</h2>
                  <p>The transfer of calf <strong>{transfer.calf.tag_number}</strong>
                     from <strong>{transfer.donor_farmer.full_name}</strong>
                     to <strong>{transfer.recipient_farmer.full_name}</strong>
                     has been completed and recorded.</p>
                  {download_section}
                  <p style="color:#9CA3AF;font-size:12px;">Girinka Pulse — Rwanda Agriculture Board</p>
                </div>
                """,
            )
            logger.info(f"Certificate email sent to {recipients}")

    except PassOnRegistry.DoesNotExist:
        logger.error(f"PassOnRegistry {transfer_id} not found.")
    except Exception as e:
        logger.error(f"Certificate generation failed for transfer {transfer_id}: {e}")
