# Generated by Django 6.0.4 on 2026-05-01 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('reading_time', models.DateTimeField()),
                ('data_source', models.CharField(default='OpenMeteo', max_length=30)),
                ('forecast_day', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='districts.district')),
            ],
            options={
                'db_table': 'weather_data',
                'ordering': ['-reading_time'],
                'indexes': [models.Index(fields=['district', 'reading_time'], name='weather_dat_distric_fa94d0_idx')],
            },
        ),
    ]
